/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_sources_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lessons */
        get: operations["lessons_api_lessons_get"];
        put?: never;
        /** Create */
        post: operations["create_api_lessons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_lessons__lid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lid}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_lessons__lid__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lid}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_lessons__lid__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lid}/shorts/{sid}/explanations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explanation */
        post: operations["explanation_api_lessons__lid__shorts__sid__explanations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lid}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_lessons__lid__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audio/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audio */
        get: operations["audio_api_audio__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandidateScore */
        CandidateScore: {
            /** Video Id */
            video_id: string;
            /** Relevance */
            relevance: number;
            /** Level Fit */
            level_fit: number;
            /** Teaching */
            teaching: number;
            /** Density */
            density: number;
            /** Captions */
            captions: number;
            /** Reason */
            reason: string;
        };
        /** Connection */
        Connection: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** CoverageEntry */
        CoverageEntry: {
            /** Short Id */
            short_id: string;
            /** Concept Id */
            concept_id: string;
            /** Learning Outcome */
            learning_outcome: string;
            /**
             * Teaching Role
             * @enum {string}
             */
            teaching_role: "foundation" | "mechanism" | "worked_example" | "comparison" | "misconception" | "application" | "practice" | "recap";
            /** Claim Summary */
            claim_summary: string;
            /** Evidence Segment Ids */
            evidence_segment_ids: string[];
            /** Example Id */
            example_id?: string | null;
            /**
             * Adds Coverage
             * @default true
             */
            adds_coverage: boolean;
        };
        /** DiagramNode */
        DiagramNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Slot */
            slot: number;
            /**
             * Shape
             * @default box
             * @enum {string}
             */
            shape: "box" | "circle" | "bar";
            /** Icon */
            icon?: string | null;
            /**
             * Role
             * @default neutral
             * @enum {string}
             */
            role: "neutral" | "start" | "step" | "result" | "warning" | "good" | "bad";
            /** Value */
            value?: number | null;
        };
        /** DiagramState */
        DiagramState: {
            /** Id */
            id: string;
            /** Target */
            target: string;
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /**
             * Role
             * @default neutral
             * @enum {string}
             */
            role: "neutral" | "start" | "step" | "result" | "warning" | "good" | "bad";
        };
        /** ErrorInfo */
        ErrorInfo: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** EvidenceRef */
        EvidenceRef: {
            /** Source Id */
            source_id: string;
            /** Segment Ids */
            segment_ids: string[];
            /** Start Ms */
            start_ms?: number | null;
            /** End Ms */
            end_ms?: number | null;
            /** Quote */
            quote: string;
        };
        /** ExampleRecord */
        ExampleRecord: {
            /** Id */
            id: string;
            /** Entities */
            entities: string[];
            /** Facts */
            facts: string[];
            /** Evidence Segment Ids */
            evidence_segment_ids: string[];
        };
        /** ExplanationRequest */
        ExplanationRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "example" | "again";
            /**
             * Added Seconds
             * @default 40
             * @constant
             */
            added_seconds: 40;
            /** Request Id */
            request_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            /** Lesson Id */
            lesson_id: string;
            /**
             * Stage
             * @default queued
             */
            stage: string;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "running" | "complete" | "failed" | "cancelled" | "interrupted";
            error?: components["schemas"]["ErrorInfo"] | null;
            /**
             * Event Sequence
             * @default 0
             */
            event_sequence: number;
            /**
             * Stage Timings
             * @default {}
             */
            stage_timings: {
                [key: string]: number;
            };
            /** Created At */
            created_at: number;
            /** Updated At */
            updated_at: number;
        };
        /** LearningRequest */
        LearningRequest: {
            /** Goal */
            goal: string;
            /**
             * Prior Knowledge
             * @default beginner
             */
            prior_knowledge: string;
            /**
             * Time Budget Seconds
             * @default 300
             */
            time_budget_seconds: number;
            /**
             * Language
             * @default en
             * @constant
             */
            language: "en";
            /** Request Id */
            request_id: string;
        };
        /** Lesson */
        Lesson: {
            /**
             * Teaching Plan Version
             * @default 1
             * @enum {integer}
             */
            teaching_plan_version: 1 | 2;
            /**
             * Examples
             * @default []
             */
            examples: components["schemas"]["ExampleRecord"][];
            /**
             * Coverage History
             * @default []
             */
            coverage_history: components["schemas"]["CoverageEntry"][];
            /**
             * Plan Diagnostics
             * @default []
             */
            plan_diagnostics: string[];
            /** Id */
            id: string;
            request: components["schemas"]["SavedLearningRequest"];
            /**
             * Objectives
             * @default []
             */
            objectives: components["schemas"]["Objective"][];
            /**
             * Short Ids
             * @default []
             */
            short_ids: string[];
            /**
             * Shorts
             * @default []
             */
            shorts: components["schemas"]["Short"][];
            /** Sources */
            sources: components["schemas"]["Source"][];
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "preparing" | "partially_ready" | "ready" | "failed" | "cancelled" | "interrupted";
            /**
             * Planned Duration Ms
             * @default 0
             */
            planned_duration_ms: number;
            /**
             * Original Planned Duration Ms
             * @default 0
             */
            original_planned_duration_ms: number;
            /**
             * Extra Allowance Ms
             * @default 0
             */
            extra_allowance_ms: number;
            job: components["schemas"]["Job"];
            /**
             * Provider Settings
             * @default {}
             */
            provider_settings: {
                [key: string]: unknown;
            };
            /**
             * Metrics
             * @default {}
             */
            metrics: {
                [key: string]: number;
            };
            /**
             * Video Rankings
             * @default []
             */
            video_rankings: components["schemas"]["CandidateScore"][];
        };
        /** NarrationUnit */
        NarrationUnit: {
            /** Text */
            text: string;
            evidence: components["schemas"]["EvidenceRef"];
            /** Beat Id */
            beat_id?: string | null;
            /** Scene Id */
            scene_id?: string | null;
            /** Purpose */
            purpose?: string | null;
            /**
             * Start Ms
             * @default 0
             */
            start_ms: number;
            /**
             * End Ms
             * @default 0
             */
            end_ms: number;
        };
        /** Objective */
        Objective: {
            /** Concept Id */
            concept_id?: string | null;
            /** Learning Outcome */
            learning_outcome?: string | null;
            /**
             * Teaching Role
             * @default foundation
             * @enum {string}
             */
            teaching_role: "foundation" | "mechanism" | "worked_example" | "comparison" | "misconception" | "application" | "practice" | "recap";
            /**
             * Dependency Ids
             * @default []
             */
            dependency_ids: string[];
            /**
             * Relevance
             * @default
             */
            relevance: string;
            /**
             * Evidence Segment Ids
             * @default []
             */
            evidence_segment_ids: string[];
            /**
             * Curriculum Role
             * @default core
             * @enum {string}
             */
            curriculum_role: "core" | "extension" | "closing";
            /**
             * Target Duration Ms
             * @default 40000
             */
            target_duration_ms: number;
            /** Example Id */
            example_id?: string | null;
            /**
             * Visual Intent
             * @default
             */
            visual_intent: string;
            /**
             * Checkpoint
             * @default false
             */
            checkpoint: boolean;
            /** Title */
            title: string;
            /**
             * Template
             * @enum {string}
             */
            template: "process" | "comparison" | "example" | "timeline" | "chart" | "steps" | "cycle" | "dos_donts" | "key_fact";
            /** Prerequisites */
            prerequisites: string[];
        };
        /** ProviderHealth */
        ProviderHealth: {
            /** Ready */
            ready: boolean;
            /** Model Ready */
            model_ready: boolean;
            /** Speech Ready */
            speech_ready: boolean;
            /** Model */
            model: string;
            /** Digest */
            digest?: string | null;
            /** Speech Provider */
            speech_provider: string;
            /** Voice */
            voice: string;
            /** Message */
            message: string;
            /**
             * Youtube Ready
             * @default false
             */
            youtube_ready: boolean;
            /**
             * Youtube Message
             * @default YouTube source setup has not been checked.
             */
            youtube_message: string;
        };
        /** Question */
        Question: {
            /** Prompt */
            prompt: string;
            /** Options */
            options: string[];
            /** Answer Index */
            answer_index: number;
            /** Explanation */
            explanation: string;
            evidence: components["schemas"]["EvidenceRef"];
            /**
             * Allowance Ms
             * @default 20000
             * @constant
             */
            allowance_ms: 20000;
        };
        /** SavedLearningRequest */
        SavedLearningRequest: {
            /** Goal */
            goal: string;
            /**
             * Prior Knowledge
             * @default beginner
             */
            prior_knowledge: string;
            /**
             * Time Budget Seconds
             * @default 300
             */
            time_budget_seconds: number;
            /**
             * Language
             * @default en
             * @constant
             */
            language: "en";
            /** Request Id */
            request_id: string;
            /** Source Mode */
            source_mode?: ("import" | "youtube") | null;
            /**
             * Source Ids
             * @default []
             */
            source_ids: string[];
        };
        /** Scene */
        Scene: {
            /** Id */
            id?: string | null;
            /**
             * Kind
             * @default diagram
             * @constant
             */
            kind: "diagram";
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Evidence References
             * @default []
             */
            evidence_references: components["schemas"]["EvidenceRef"][];
            /**
             * Beat Ids
             * @default []
             */
            beat_ids: string[];
            /**
             * States
             * @default []
             */
            states: components["schemas"]["DiagramState"][];
            /**
             * Template
             * @enum {string}
             */
            template: "process" | "comparison" | "example" | "timeline" | "chart" | "steps" | "cycle" | "dos_donts" | "key_fact";
            /** Nodes */
            nodes: components["schemas"]["DiagramNode"][];
            /** Connections */
            connections: components["schemas"]["Connection"][];
            /** Actions */
            actions: components["schemas"]["SceneAction"][];
            /**
             * Start Ms
             * @default 0
             */
            start_ms: number;
            /** End Ms */
            end_ms: number;
        };
        /** SceneAction */
        SceneAction: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "appear" | "disappear" | "highlight" | "move" | "draw" | "change_state";
            /** Target */
            target: string;
            /** At Ms */
            at_ms: number;
            /** To Slot */
            to_slot?: number | null;
            /** State Id */
            state_id?: string | null;
            /** Beat Id */
            beat_id?: string | null;
        };
        /** SearchItem */
        SearchItem: {
            /** Video Id */
            video_id: string;
            /** Title */
            title: string;
            /** Channel */
            channel: string;
            /** Url */
            url: string;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /**
             * Transcript Status
             * @default needed
             * @constant
             */
            transcript_status: "needed";
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["SearchItem"][];
            /** Cached */
            cached: boolean;
            /**
             * Acquisition
             * @default assisted
             * @constant
             */
            acquisition: "assisted";
        };
        /** Short */
        Short: {
            /** Concept Id */
            concept_id?: string | null;
            /** Learning Outcome */
            learning_outcome?: string | null;
            /** Teaching Role */
            teaching_role?: ("foundation" | "mechanism" | "worked_example" | "comparison" | "misconception" | "application" | "practice" | "recap") | null;
            /**
             * Curriculum Role
             * @default core
             * @enum {string}
             */
            curriculum_role: "core" | "extension" | "closing";
            /** Example Id */
            example_id?: string | null;
            /**
             * Source Review Status
             * @default unchecked
             * @enum {string}
             */
            source_review_status: "unchecked" | "model_supported";
            /**
             * Source Review Reason
             * @default
             */
            source_review_reason: string;
            /**
             * Teaching Diagnostics
             * @default []
             */
            teaching_diagnostics: string[];
            /**
             * Review Repair Reasons
             * @default []
             */
            review_repair_reasons: string[];
            /**
             * Storyboard Version
             * @default 1
             * @enum {integer}
             */
            storyboard_version: 1 | 2;
            /** Timeline Compiler Version */
            timeline_compiler_version?: string | null;
            /** Id */
            id: string;
            /** Objective */
            objective: string;
            /**
             * Prerequisites
             * @default []
             */
            prerequisites: string[];
            /**
             * Narration Units
             * @default []
             */
            narration_units: components["schemas"]["NarrationUnit"][];
            /**
             * Evidence References
             * @default []
             */
            evidence_references: components["schemas"]["EvidenceRef"][];
            /**
             * Scenes
             * @default []
             */
            scenes: components["schemas"]["Scene"][];
            question?: components["schemas"]["Question"] | null;
            /** Audio Path */
            audio_path?: string | null;
            /**
             * Measured Duration Ms
             * @default 0
             */
            measured_duration_ms: number;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "generating" | "validating" | "synthesizing" | "ready" | "failed" | "cancelled";
            error?: components["schemas"]["ErrorInfo"] | null;
            /**
             * Optional
             * @default false
             */
            optional: boolean;
            /**
             * Question Required
             * @default false
             */
            question_required: boolean;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            /**
             * Provider Settings
             * @default {}
             */
            provider_settings: {
                [key: string]: unknown;
            };
            /**
             * Timings
             * @default {}
             */
            timings: {
                [key: string]: number;
            };
        };
        /** Source */
        Source: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "original_sample" | "import" | "youtube";
            /** Video Id */
            video_id?: string | null;
            /** Url */
            url?: string | null;
            /** Channel */
            channel?: string | null;
            /** Transcript Provider */
            transcript_provider?: ("youtube-transcript-api" | "supadata") | null;
            /**
             * Transcript Status
             * @enum {string}
             */
            transcript_status: "available" | "needed";
            /** Provenance */
            provenance: string;
            /** Content Hash */
            content_hash: string;
            /**
             * Segments
             * @default []
             */
            segments: components["schemas"]["TranscriptSegment"][];
        };
        /** SourceList */
        SourceList: {
            /** Sources */
            sources: components["schemas"]["Source"][];
        };
        /** TranscriptSegment */
        TranscriptSegment: {
            /** Id */
            id: string;
            /** Source Id */
            source_id: string;
            /** Text */
            text: string;
            /** Start Ms */
            start_ms?: number | null;
            /** End Ms */
            end_ms?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readiness_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderHealth"];
                };
            };
        };
    };
    sources_api_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
        };
    };
    search_api_sources_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lessons_api_lessons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"][];
                };
            };
        };
    };
    create_api_lessons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_lessons__lid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_lessons__lid__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_lessons__lid__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explanation_api_lessons__lid__shorts__sid__explanations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lid: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplanationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_lessons__lid__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                lid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audio_api_audio__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
